- name: Setup Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Create github runner user
  ansible.builtin.user:
    name: github

- name: Create github actions folder
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github
    group: github

- name: chekc already runner configured status
  ansible.builtin.stat:
    path: /actions-runner/.runner
  register: runner_stat

- name: debug
  debug:
    msg: "{{ runner_stat }}"

- name: Download github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.325.0/actions-runner-linux-x64-2.325.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes
  when: not stat.exists

- name: Install libicu dependency package
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Configure Github runner
  ansible.builtin.shell: ./config.sh --url https://github.com/aminrana37 --token AHRVVYSKIF2QYIQIJAIDTD3INILVY --unattended
  args:
    chdir: /actions-runner
  become_user: github

#- name: Configure Github runner
#  ansible.builtin.shell: ./run.sh
#  args:
#    chdir: /actions-runner
#  become_user: github